### PR TITLE
Added checking for spaces in username

### PR DESCRIPTION
**Pull request by kumouri**
I added in checking for spaces in usernames and removing them (reading the thread on Reddit it looked like people have had success with simply removing spaces from their names), as well as moved removing uppercase letters to the constructor of the Login class. 

In case that is the wrong way to say it, I come from a C++ background and haven't done much with C# yet. That is what it would be called in C++, though.

### CODE REVIEW

**Comment by encratite** [comment]
Oh, I'm afraid I already fixed this just a few minutes ago. By the way, spaces are not even possible in usernames. I noticed that just now when I was running some tests. But thanks for trying anyways.

Also, the lower casing is only required for the Flex service, not for the LQ service. This is why I didn't mess with the Login class itself.

See:

https://github.com/epicvrvs/RiotControl/commit/e7497d04ccbf7e3836fc08e29b76bf9db7e1a3c9

**Comment by kumouri** [comment]
I believe spaces were possible in usernames a while back (in the first couple of months, I'm not sure when they stopped this, though). For example, Dyrus has a smurf account (not really a smurf anymore) on EU with the username WORST TOP NA. 

And I was wondering why you had it in the function call instead of inside the constructor and that makes sense. I didn't think about that.

**Comment by encratite** [comment]
Are you sure that that is his actual account name? I know that this is his summoner name but is it really his account name? I've seen him logging in on that summoner name and IIRC his account name was something like "dyrusna".

**Comment by kumouri** [comment]
I'm honestly not sure. It might be worth it to implement the check anyway, just in case someone has spaces. Although I would move it into the Flex login section, which I can do in a minute.

**Comment by encratite** [comment]
Nah, I'm not comfortable with this until we have actual proof that this does in fact occur. Otherwise it might result in incompatibilities in future when they move on to a more liberal account name system.

**Pull request closed without merging**
