### PR TITLE
Fixed 2 files needed to compile in linux

### PR DESCRIPTION
**Pull request by tsubus**
These changes allow for a successful compilation of RiotGear and RiotShield in linux (with mono's xbuild). To compile RiotUpdate you would need to fix another file that most likely would break compilation in Windows, so I am not requesting a pull of that file. Look in my repo if needed (master branch).

### CODE REVIEW

**Comment by Korbeil** [comment]
For the RiotGear.dll path, that's work only on linux
That is why i prefer to add a "cp" command in my script

**Comment by tsubus** [comment]
Hm, if that's the case (I haven't checked, I really don't feel like installing Visual Studio and whatnot), then something is wrong...RiotGear.dll should be built in the same folder, no matter the OS.

**Comment by tsubus** [comment]
another fix for the search form

**Comment by tsubus** [comment]
fixed another bug with the web interface...manual update had the wrong privileges

**Comment by encratite** [comment]
This is bizarre, why haven't I noticed this until now :( I can't believe this has been here for 5 months without any reactions, I'm so sorry. Not entirely sure if it's worth gonig through these at this point since the project is largely dead.

**Comment by phate45** [comment]
Well, sometimes it's good to take a break from a project, but I can assure you, it's not so close to death as you imagine. Carry on the good work!

**Pull request closed without merging**
