### PR TITLE
Update SummonerRating.js

### PR DESCRIPTION
**Pull request by Rejna**
Quick fix for "api error" posted lately. Both js and c# codes need some review about what data we can fetch from Riot and what we record locally.

### CODE REVIEW

**Comment by genesisdk** [comment]
Rejna is it possible you could help me set this up for my server you seem to quite a bit understanding of this, i'm only  learning  php css  and html, so  with this c# and ruby  xml, and so on i have no idea how to set it up for my server. and i need it for a project . if you could i would be most greatfull :)

**Comment by Rejna** [comment]
I'd love to but right now I'm busy. I got my deadlines for semester projects and I have much work. I will be free after 21 June. If it is not too late, you can ask me then. Earlier I can't.

**Comment by genesisdk** [comment]
ok   no its not to late   ill ask  again 21 of june.
 is it possible to exchange skype or mail so we  dont spam this pull request , as it would be a shame .
and write without   giving  needless info here.

**Comment by encratite** [comment]
Argh, so many whitespace modifications in this one. Makes it difficult to see what you actually changed. Alright, so it looks like you enabled the "dumbed down" stats mode for all entries. I suppose I can do that but I'm not going to merge this one.

**Comment by encratite** [comment]
Oh, wow, I see where all those API errors came from. It was caused by me accidentally generating incompatible databases for a format that hadn't been fully developed yet. I was supposed to keep on using the old SQLite file for that generator. What a mess. I also updated that table, although in a different way.

**Comment by genesisdk** [comment]
hi rejna   i have no other means  than to write here , i was wondering if, ur time has freed  up from exams.

if yes contact  me on mail :  clj2ownz@gmail.com OR skype : cliexe

**Pull request closed without merging**
